# Generated by Django 6.0.6 on 2026-06-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True)),
                ('station_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadeduvwfile',
            name='observation_time',
        ),
        migrations.RemoveField(
            model_name='uploadeduvwfile',
            name='station_name',
        ),
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.station'),
        ),
    ]
