# Generated by Django 6.0.6 on 2026-06-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_station_remove_uploadeduvwfile_observation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='baud_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WindReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_km', models.FloatField()),
                ('u', models.FloatField()),
                ('v', models.FloatField()),
                ('w', models.FloatField()),
                ('uvw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_readings', to='dashboard.uploadeduvwfile')),
            ],
            options={
                'ordering': ['height_km'],
            },
        ),
    ]
