# Generated by Django 6.0.6 on 2026-06-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_uploadeduvwfile_baud_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='station_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadeduvwfile',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10),
        ),
    ]
