# Generated by Django 6.0.6 on 2026-06-30 08:24

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_uploadeduvwfile_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeduvwfile',
            name='file',
            field=models.FileField(upload_to=dashboard.models.uvw_upload_path),
        ),
    ]
