# Generated by Django 6.0.6 on 2026-07-09 08:44

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_maplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeduvwfile',
            name='file',
            field=models.FileField(storage=dashboard.models.UVWUploadStorage(), upload_to=dashboard.models.uvw_upload_path),
        ),
    ]
